package pk.edu.nust.seecs.gradebook.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Returns a Course Learning Outcome entity object.
 * <p>
 * This entity class holds the general attributes of a clo.
 * Contained in this class are attributes such as name, description, PLO, and BTLevel.
 */
@Entity
public class CLO implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "clo_id")
    private Integer cloId;
    @Column
    private String name;
    @Column
    private String description;
    @Column
    private String PLO;
    @Column
    private String btLevel;

    /*
    * Class constructor that takes in a name, description, PLO and btlevel to
    * build this object
    */
    public CLO(String name, String description, String PLO, String btLevel) {
        this.name = name;
        this.description = description;
        this.PLO = PLO;
        this.btLevel = btLevel;
    }

    /*
    * Class constructor.
    */
    public CLO() {
    }

    /*
    * Class constructor that creates this object by passing a string name.
    */
    public CLO(String name) {
        this.name = name;
    }

    /*
    * This method will return the id of this Course Learning Outcome.
    * Note; we have not defined any setter method for clo id, since it is 
    * to be generated by the dbms.
    */
    public Integer getCloId() {
        return cloId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPLO() {
        return PLO;
    }

    public void setPLO(String PLO) {
        this.PLO = PLO;
    }

    public String getBtLevel() {
        return btLevel;
    }

    public void setBtLevel(String btLevel) {
        this.btLevel = btLevel;
    }

    @Override
    public String toString() {
        return "CLO{" + "cloId=" + cloId + ", name=" + name + ", description=" + description + ", PLO=" + PLO + ", btLevel=" + btLevel + '}';
    }

}
