package pk.edu.nust.seecs.gradebook.entity;

import javax.persistence.*;
import java.util.*;

/**
 * Returns a Content entity object that holds everything related to a typical
 * content in a course.
 * <p>
 * This entity class holds the general attributes of a content.
 * Contained in this class are attributes such as title(Assignment 1), description,
 * a startTime, endTime for it, students, the course it belongs to, grades and CLO.
 */
@Entity
public class Content implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "content_id")
    private Integer contentId;
    @Column
    private String title;
    @Column
    private String description;
    @Column
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date startTime;
    @Column
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date endTime;
    /*
        * This relationship contains the students associated with this content.
        * The reverse relationship is present in the Student entity class
        */
    @ManyToMany(cascade = {CascadeType.ALL})
    @JoinTable(name = "content_students", joinColumns = {
            @JoinColumn(name = "content_id")}, inverseJoinColumns = {
            @JoinColumn(name = "student_id")})
    private Set<Student> students = new HashSet<>(0);
    /*
    * This relationship contains the course this content belongs to.
    * The reverse relationship is present in the Course entity class
    */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = false)
    private Course course;

    /*
    * This relationship contains the grades marked against this content.
    * The reverse relationship is present in the Grade entity class
    */
    @OneToMany
    private Set<Grade> grades = new HashSet<>(0);
    /*
    * This relationship contains the CLO mapped to this content.
    * This should be converted to a 1-1 mapping, since only 1 CLO can map to a content.
    * The reverse relationship is present in the CLO entity class
    */
    @OneToMany
    private List<CLO> CLO = new ArrayList<>();

    /*
    * Class constructor.
    */
    public Content() {
    }

    public Set<Grade> getGrades() {
        return grades;
    }

    public void setGrades(Set<Grade> grades) {
        this.grades = grades;
    }

    /*
    * This method will return the id of this content.
    * Note; we have not defined any setter method for content id, since it is
    * to be generated by the dbms.
    */
    public Integer getContentId() {
        return contentId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<CLO> getCLO() {
        return CLO;
    }

    public void setCLO(List<CLO> CLO) {
        this.CLO = CLO;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Set<Student> getStudents() {
        return students;
    }

    public void setStudents(Set<Student> students) {
        this.students = students;
    }

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    @Override
    public String toString() {
        return "Content{" + "contentId=" + contentId + ", title=" + title + ", description=" + description + ", startTime=" + startTime + ", endTime=" + endTime + ", students=" + students + ", course=" + course + ", grades=" + grades + ", CLO=" + CLO + '}';
    }


}
